spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
      show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${AWS_RDS_ENDPOINT}:${AWS_RDS_PORT_NUMBER}/${AWS_RDS_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
  flyway:
    enabled: false
cloud:
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket-name: ${AWS_S3_BUCKET_NAME}
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus